import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {resolve,join} from 'node:path';
import {rmSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {fixture} from './fixture.js';
const {root}=fixture();
execFileSync(process.execPath,[resolve('dist/cli.cjs'),'build',root,'--branch','main','--branch','team/integration','--history-days','3650']);
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors:string[]=[],requests:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
 await page.goto(pathToFileURL(join(root,'branchquilt/index.html')).href);
 assert(await page.locator('#files-panel').isHidden());assert(await page.locator('#activity-panel').isHidden());
 assert(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight));
 await page.getByRole('button',{name:'Open details: src',exact:true}).click();await page.waitForSelector('#inspector:not([hidden])');
 assert((await page.locator('#details').textContent())!.includes('directory'));
 await page.getByRole('button',{name:'Open details: src',exact:true}).click();assert(await page.locator('#inspector').isHidden());
 await page.getByRole('button',{name:'src/',exact:true}).click();assert((await page.locator('#breadcrumbs').textContent())!.includes('src'));assert((await page.locator('.tile[data-path="src"]').getAttribute('class'))!.includes('expanded'));
 await page.getByRole('button',{name:'auth.ts',exact:true}).click();await page.getByRole('button',{name:'login',exact:true}).first().click();assert((await page.locator('#details').textContent())!.includes('UTF-8'));await page.keyboard.press('Escape');
 await page.locator('#compare').selectOption('1');assert.equal(await page.locator('.pane').count(),2);
 await page.getByRole('button',{name:'Search /'}).click();await page.locator('#search').fill('review');await page.locator('#file-list button').click();assert((await page.locator('#details').textContent())!.includes('absent'));
 await page.locator('#branch').selectOption('1');await page.locator('#search').fill('');
 await page.getByRole('button',{name:'Activity',exact:true}).click();await page.locator('.event').first().click();assert((await page.locator('#details').textContent())!.includes('Morgan'));
 await page.keyboard.press('Escape');assert(await page.locator('#inspector').isHidden());
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 await page.keyboard.press('Escape');
 await page.locator('#color-mode').selectOption('ownership');
 await page.keyboard.press('/');await page.locator('#contributor').selectOption({label:'Morgan'});
 assert((await page.locator('#legend').textContent())!.includes('Morgan'));
 await page.keyboard.press('Escape');
 await page.screenshot({path:resolve('work/phase2-browser.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight));
 console.log('Browser passed: local file, no external requests, drilldown, paired maps, search, inspector toggle, hostile metadata, timeline, Escape.');
}finally{await browser.close();rmSync(root,{recursive:true,force:true});}
